### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by zhangyumin** [arnaudceol/htsflow#1]
![1](https://cloud.githubusercontent.com/assets/12167456/14775309/bc76f210-0af0-11e6-90f8-acceae273f64.png)
I've changed the permission of those files, but it still not works.

**Comment by arnaudceol** [comment]
Hi, and thanks for trying HTS-flow.

Could you show me the permissions for this file (htsflow.ini)? This file is accessed by the apache user (in your case www-data), not only by yourself. May it be the problem?

Arnaud

**Comment by zhangyumin** [comment]
![2](https://cloud.githubusercontent.com/assets/12167456/14821603/fa05190a-0bfd-11e6-8567-f015142bf66b.png)
and
![1](https://cloud.githubusercontent.com/assets/12167456/14821604/fa2fe766-0bfd-11e6-81dc-cefd9512d7c5.png)

I changed the owner of this file, but still permission denied

**Comment by zhangyumin** [comment]
I just move the whole htsflow files to /var/www. and finally i can open the index page.
it seems that the apache user(www-data) can only read files from /var/www directory.
so there must be some configurations in apache or php5 that control the read permission.
And thank you for your answer.

**Comment by arnaudceol** [comment]
Great. I'm glad you found the solution, and thanks for sharing it.
